
export interface ImageData {
  id: string;
  src: string;
  alt: string;
  title: string;
  description?: string;
  category: 'heritage' | 'biography' | 'interactive' | 'timeline';
}

// Thonet-themed comic-style images generated by our SVG endpoint
export const imageData: ImageData[] = [
  {
    id: 'thonet-chair-1',
    src: '/api/placeholder/400/400?theme=chair',
    alt: 'Klasyczne krzesło Thonet w stylu komiksowym',
    title: 'Krzesło Nr. 14',
    description: 'Kultowe krzesło Thonet w komiksowej stylizacji',
    category: 'heritage'
  },
  {
    id: 'thonet-chair-2',
    src: '/api/placeholder/350/400?theme=chair',
    alt: 'Inny model krzesła Thonet w stylu komiksowym',
    title: 'Krzesło Wiedeńskie',
    description: 'Eleganckie krzesło z giętego drewna',
    category: 'heritage'
  },
  {
    id: 'thonet-workshop',
    src: '/api/placeholder/500/350?theme=workshop',
    alt: 'Warsztat Thonet w stylu komiksowym',
    title: 'Warsztat Mistrza',
    description: 'Proces tworzenia mebli w XIX wieku',
    category: 'interactive'
  },
  {
    id: 'steam-process',
    src: '/api/placeholder/450/300?theme=process',
    alt: 'Proces gięcia drewna na parze w stylu komiksowym',
    title: 'Technologia Pary',
    description: 'Innowacyjny proces gięcia drewna',
    category: 'interactive'
  },
  {
    id: 'michael-thonet',
    src: '/api/placeholder/350/450?theme=portrait',
    alt: 'Michael Thonet w stylu komiksowym',
    title: 'Michael Thonet',
    description: 'Portret założyciela firmy',
    category: 'biography'
  },
  {
    id: 'bentwood-process',
    src: '/api/placeholder/400/300?theme=process',
    alt: 'Proces gięcia drewna w stylu komiksowym',
    title: 'Gięcie Drewna',
    description: 'Rewolucyjna technika produkcji',
    category: 'timeline'
  },
  {
    id: 'workshop-tools',
    src: '/api/placeholder/400/350?theme=workshop',
    alt: 'Narzędzia warsztatowe w stylu komiksowym',
    title: 'Narzędzia Rzemiosła',
    description: 'Tradycyjne narzędzia stolarskie',
    category: 'timeline'
  },
  {
    id: 'chair-collection',
    src: '/api/placeholder/500/400?theme=chair',
    alt: 'Kolekcja krzeseł Thonet w stylu komiksowym',
    title: 'Kolekcja Thonet',
    description: 'Różnorodność projektów mebli',
    category: 'heritage'
  }
];

export const getImagesByCategory = (category: ImageData['category']) => {
  return imageData.filter(img => img.category === category);
};
